config/routes.rb
Rails.application.routes.draw do
  root to: "home#show"

  get 'profile', to: 'home#profile'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
require "clerk/authenticatable"

class ApplicationController < ActionController::Base
  include Clerk::Authenticatable

  helper_method :current_user

  def current_user
    @current_user ||= clerk_user
  end

  protected

  def require_login
    if !current_user
      flash[:error] = "You must be logged in to access the page at `#{request.path}` <br/> Please login and retry."

      redirect_to root_url
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :require_login, only: :profile

  def show
  end

  # GET /profile
  def profile
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def clerk_script_tag
    script_url = ENV["CLERKJS_SCRIPT_URL"].presence ||
      "https://#{ENV.fetch('CLERK_FRONTEND_API')}/npm/@clerk/clerk-js@staging/dist/clerk.browser.js"

    javascript_include_tag(
      script_url,
      {
        'data-clerk-frontend-api': ENV.fetch('CLERK_FRONTEND_API'),
        crossorigin: 'anonymous',
        onload: 'startClerk()',
        defer: true,
      }
    )
  end
end

app/views/home/profile.html.erb
<h1>My Profile (protected page)</h1>

<p>This is your personal profile page - only you can access it!</p>

<p>
NOTE: This is an authenticated route; it's only rendered if there's a
currently logged in user.
</p>

app/views/home/show.html.erb
<h1>Welcome to the homepage!</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Clerk Rails Starter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style type="text/css" media="screen" charset="utf-8">
      body {
        font-family: Georgia, sans-serif;
        line-height: 2rem;
        font-size: 1.3rem;
        background-color: white;
        margin: 0;
        padding: 0;
        color: #000;
      }

      h1 {
        font-weight: normal;
        line-height: 2.8rem;
        font-size: 2.5rem;
        letter-spacing: -1px;
        color: black;
      }

      p { font-family: monospace; }

      .navbar {
        display: flex;
        justify-content: flex-end;
        align-items: center;
        height: 68px;
        line-height: 68px;
        font-size: 1rem;
        text-align: right;
        padding: 0 1.5rem;
      }

      .navbar a {
        display: inline-block;
        margin-right: 1.5rem;
        font-weight: bold;
        color: #CC0000;
      }

      .navbar button {
        background: #CC0000;
        box-shadow: 0px 2px 0px #FF9999;
        border: none;
        border-radius: 10px;
        color: white;
        font-family: inherit;
        font-size: 1rem;
        padding: 8px 16px;
      }

      .container {
        max-width: 960px;
        margin: 0 auto 40px;
        overflow: hidden;
      }

      .logos img {
        vertical-align: bottom;
      }

      .logos a {
        display: inline-block;
      }

      .plus {
        display: inline-block;
        font-family: Georgia, sans-serif;
        font-size: 36px;
        padding: 0 8px;
      }

      section {
        margin: 0 auto 2rem;
        padding: 1rem 0 0;
        text-align: center;
      }

      @media only screen and (max-width: 500px) {
        h1 { font-size: 2rem; }

        .version { font-size: 1.1rem; }
      }

      .welcome {
        width: 600px;
        max-width: 100%;
        height: auto;
      }
    </style>

    <%= clerk_script_tag %>
  </head>

  <body>
    <nav class="navbar">
      <% if current_user.present? %>
        <!-- Clerk UserButton -->
        <div id="user-button"></div>
      <% else %>
        <!-- Clerk Sign up and Sign in links -->
        <a href="javascript:void(0)" onclick="Clerk.openSignIn()" data-turbolinks="false">Sign in</a>
        <button onclick="Clerk.openSignUp()">Sign up</button>
      <% end %>
    </nav>
    <div class="container">
      <section>
        <% flash.each do |type, msg| %>
          <div style="color: white; background-color: red; margin: 10px; padding: 10px;">
            <%= msg.html_safe %>
          </div>
        <% end %>

        <p>Menu:
          <%= link_to 'Home', root_path %> |
          <%= link_to 'My Profile', profile_path %> |
          <%= link_to 'Accounts (external)', ENV["CLERK_ACCOUNTS_URL"], target: "_blank" %>
        </p>

        <%= yield %>

        <p style="font-size: 18px; color: #666;">
          <% if current_user.present? %>
            You are logged in!
          <% else %>
            You are logged out.
          <% end %>
        </p>

        <br /><br />
        <section style="margin: 10; padding: 10px; font-size: 14px;
          text-align: left; border: 1px solid; color: #333">
          <strong>clerk_session (requests API the 1st time)</strong>:
          <br /><%= clerk_session.inspect %>
          <hr/>
          <strong>clerk_user (requests API; cached afterwards):</strong>
          <br /><%= current_user.inspect %>
          <hr/>
          <strong>clerk_reverify_session! (requests API)</strong>:
          <br /><%= clerk_reverify_session!.inspect %>
          <hr/>
          <strong>clerk_user_id:</strong>
          <br /><%= clerk_user_id.inspect %>
          <hr/>
          <strong>clerk_user:</strong>
          <br /><%= current_user.inspect %>
          <hr/>
          <strong>clerk_verified_session_claims:</strong>
          <br /><%= clerk_verified_session_claims.inspect %>
          <hr/>
          <strong>clerk_verified_session_token:</strong>
          <br /><%= clerk_verified_session_token.inspect %>
        </section>
      </section>
    </div>
  </body>
</html>